version: '3.0'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - electrokerot-redis:/data
    networks:
      - electrokerot-scrapper-network
    expose:
      - '6379'
    command: redis-server --save 30 1 --loglevel warning
  mongodb:
    image: mongo
    restart: always
    volumes:
      - electrokerot-mongodb:/data/db
    networks:
      - electrokerot-scrapper-network
    ports:
      - '27017:27017'
  scrapper:
    image: node:18-alpine3.15
    depends_on:
      - redis
      - mongodb
    restart: always
    volumes:
      - ../electrokerot-scrapper:/app
      - /app/node_modules
    networks:
      - electrokerot-scrapper-network
    working_dir: /app
    command: sh -c "npm install && npm start"
  msa-db-updater:
    image: node:18-alpine3.15
    depends_on:
      - redis
      - mongodb
    restart: always
    volumes:
      - ../electrokerot-msa-db-updater:/app
      - /app/node_modules
    networks:
      - electrokerot-scrapper-network
    expose:
      - '10000'
    working_dir: /app
    command: sh -c "npm install && npm start"
  crawler:
    image: node:18-alpine3.15
    depends_on:
      - redis
      - mongodb
    restart: always
    volumes:
      - ../electrokerot-crawler:/app
      - /app/node_modules
    networks:
      - electrokerot-scrapper-network
    expose:
      - '20000'
    working_dir: /app
    command: sh -c "npm install && npm start"
volumes:
  electrokerot-mongodb:
    external: true
  electrokerot-redis:
    external: true
networks:
  electrokerot-scrapper-network:
